// MCPLISTCSATORNA921 -- the warning that ships to every agent's CLAUDE.md.
//
// Why a section and not a doc alone: the reader we are trying to reach is the
// agent that OWNS a channel and reaches for `claude mcp list` as a health
// check. A doc nobody opens does not reach that reader. The section is kept to
// a few lines and points at docs/mcp-list-channel-plugin.md for the evidence,
// because per-session context is a real cost.
//
// Why the wiring assertions matter (TGSABLONHOOK921, 2026-09-21): a block that
// lands only in the template reaches NEW agents and never the existing ones.
// The generator must be called from BOTH surfaces: web.ts for the main agent
// and agent-process.ts for every other agent.
//
// Source-level assertions, matching the sibling scaffold tests.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..', '..')
const SCAFFOLD = readFileSync(join(__dirname, '..', 'web', 'agent-scaffold.ts'), 'utf-8')
const WEB = readFileSync(join(__dirname, '..', 'web.ts'), 'utf-8')
const AGENT_PROCESS = readFileSync(join(__dirname, '..', 'web', 'agent-process.ts'), 'utf-8')
const DOC = readFileSync(join(ROOT, 'docs', 'mcp-list-channel-plugin.md'), 'utf-8')

const body = SCAFFOLD.slice(
  SCAFFOLD.indexOf('function buildMcpListChannelBody('),
  SCAFFOLD.indexOf('const EVIDENCE_BEGIN'),
)

describe('mcp-list channel warning: what it says', () => {
  it('names the SCOPE (a channel-owning session), not a blanket ban on the command', () => {
    expect(body).toMatch(/csatornát birtokol/)
    // The command stays legitimate elsewhere; a prohibition that reads as
    // general would be false on a customer machine.
    expect(body).toMatch(/hasznos diagnosztika/)
  })

  it('carries the measurement date, because a behaviour claim without one rots silently', () => {
    expect(body).toMatch(/2026-09-21/)
  })

  it('says the command does NOT report the failure (exit 0 and "Connected")', () => {
    expect(body).toMatch(/Connected/)
    expect(body).toMatch(/0-val tér vissza|nem jelzi/)
  })

  it('states the recovery, so the reader is not left with a dead channel', () => {
    expect(body).toMatch(/újraindítása visszahozza/)
  })

  it('marks the INBOUND leg as NOT measured by us', () => {
    expect(body).toMatch(/BEJÖVŐ[\s\S]{0,60}nem mértük/)
  })

  it('points at the evidence doc instead of inlining it (per-session context costs)', () => {
    expect(body).toMatch(/docs\/mcp-list-channel-plugin\.md/)
    // Keep the seeded surface small: a few lines, not a page.
    const lines = (body.match(/^\s+'/gm) || []).length
    expect(lines).toBeLessThanOrEqual(16)
  })
})

describe('mcp-list channel warning: where it lands', () => {
  it('is generated by an ensure* function with begin/end markers', () => {
    expect(SCAFFOLD).toContain('export function ensureMcpListChannelSection(name: string): void {')
    expect(SCAFFOLD).toContain("MCPLIST_BEGIN = '<!-- BEGIN GENERATED: mcp-list-channel")
    expect(SCAFFOLD).toContain("MCPLIST_END = '<!-- END GENERATED: mcp-list-channel")
  })

  it('reaches the MAIN agent (web.ts)', () => {
    expect(WEB).toContain('ensureMcpListChannelSection(MAIN_AGENT_ID)')
  })

  it('reaches EVERY OTHER agent, including ones that already exist (agent-process.ts)', () => {
    expect(AGENT_PROCESS).toContain('ensureMcpListChannelSection(name)')
  })
})

describe('mcp-list channel warning: the evidence doc', () => {
  it('separates what was measured from what was not', () => {
    expect(DOC).toMatch(/Amit a mérés MEGÁLLAPÍT/)
    expect(DOC).toMatch(/Amit a mérés NEM állapít meg/)
    expect(DOC).toMatch(/külső beküldő mérte/)
  })

  it('records the before-state as a separate round, which is what makes the after meaningful', () => {
    expect(DOC).toMatch(/két külön körben|KÜLÖN körben/)
  })
})
