#!/usr/bin/env python3
"""EMAILKAPU901 PR1: byte-parity of the extracted email_extract module.

Three layers, because a green diff alone proves nothing:
 1. GOLDEN PARITY -- collect_bash_body/collect_mcp_body outputs must be
    byte-identical to a golden captured from the PRE-refactor
    outgoing-copy-gate.py (fixtures/email-extract-golden.json, generated by
    helpers/gen-email-extract-golden.py at commit 8ccacdf8). Covers the four
    mandated forms (inline --body, < /abs/path, $(cat), $VAR) plus backtick,
    ${var}, heredoc, unresolvable path, missing file, pipe, and the MCP field
    set -- including the exact unreadable_reason strings.
 2. MUTATION CANARIES -- each guarded branch is deliberately broken in an
    exec'd copy of the module source, and the test asserts parity WOULD fail.
    If a canary passes parity, the comparison is not looking at that branch.
 3. IMPORT FAIL-CLOSED -- the gate copied WITHOUT email_extract.py must still
    BLOCK a send (exit 2), never slip to exit 1 (non-blocking in PreToolUse).

Plus expected-value tests for the NEW recipient extraction (to/cc share the
body's deterministic-or-deny boundary) and the envelope composition.

Run: python3 <thisfile>   Exit 0 = all pass.
"""
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
HOOKS = os.path.join(os.path.dirname(HERE), "hooks")
MODULE = os.path.join(HOOKS, "email_extract.py")
GATE = os.path.join(HOOKS, "outgoing-copy-gate.py")
GOLDEN = os.path.join(HERE, "fixtures", "email-extract-golden.json")
BODY_FILE = os.path.join(HERE, "fixtures", "email-extract-body.txt")
BODY_FILE_LATIN1 = os.path.join(HERE, "fixtures", "email-extract-body-latin1.txt")

failed = []


def check(name, ok, detail=""):
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" -- {detail}" if not ok and detail else ""))
    if not ok:
        failed.append(name)


def load_from_source(source, tag):
    mod_ns = {}
    code = compile(source, f"email_extract<{tag}>", "exec")
    exec(code, mod_ns)  # noqa: S102 -- test-only, our own source
    return mod_ns


def run_parity(ns, golden):
    """Return list of (case, what, got, want) mismatches."""
    mismatches = []
    for name, case in golden["bash"].items():
        cmd = case["cmd_template"].replace("{BODY_FILE_LATIN1}", BODY_FILE_LATIN1).replace("{BODY_FILE}", BODY_FILE)
        text, reason = ns["collect_bash_body"](cmd)
        if text != case["text"]:
            mismatches.append((name, "text", text, case["text"]))
        if reason != case["reason"]:
            mismatches.append((name, "reason", reason, case["reason"]))
    for name, case in golden["mcp"].items():
        text = ns["collect_mcp_body"](case["tool_input"])
        if text != case["text"]:
            mismatches.append((name, "text", text, case["text"]))
    return mismatches


with open(GOLDEN, encoding="utf-8") as fh:
    golden = json.load(fh)
with open(MODULE, encoding="utf-8") as fh:
    module_source = fh.read()

# --- 1. golden parity on the real module -------------------------------------
spec = importlib.util.spec_from_file_location("email_extract_under_test", MODULE)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
real_ns = {"collect_bash_body": mod.collect_bash_body,
           "collect_mcp_body": mod.collect_mcp_body}

mismatches = run_parity(real_ns, golden)
for case, what, got, want in mismatches:
    print(f"       parity mismatch {case}/{what}: got={got!r} want={want!r}")
check(f"golden parity: {len(golden['bash'])} bash + {len(golden['mcp'])} mcp cases byte-identical",
      not mismatches)

# --- 2. mutation canaries: prove the parity check LOOKS at each branch -------
CANARIES = [
    ("substitution-boundary regex broken -> $(cat) branch must fail parity",
     r"\$\(|`|\$\{?\w", r"\$NEVERMATCH\(", "subst-dollar-paren"),
    ("redirect file-read mutated (strip) -> < /abs/path branch must fail parity",
     "parts.append(fh.read())", "parts.append(fh.read().strip())", "redirect-abs-file"),
    ("MCP field set loses 'subject' -> mcp branch must fail parity",
     '"body", "text", "html", "htmlBody", "message", "subject", "content"',
     '"body", "text", "html", "htmlBody", "message", "content"', "mcp-body-subject"),
    # this one needs the latin-1 fixture: on clean UTF-8 the mutation is
    # behavior-equivalent (found by an external mutation probe during PR1)
    ("decode policy replace->ignore -> invalid-utf8 branch must fail parity",
     'errors="replace"', 'errors="ignore"', "redirect-invalid-utf8"),
]
for name, old, new, expect_case in CANARIES:
    assert old in module_source, f"canary target not found in module source: {old!r}"
    mutated = module_source.replace(old, new, 1)
    ns = load_from_source(mutated, name)
    muts = run_parity(ns, golden)
    hit = any(c == expect_case for c, *_ in muts)
    check(f"canary: {name}", hit,
          f"mutation was NOT caught (mismatches: {[c for c, *_ in muts]})")

# --- 3. gate without the module: send still BLOCKS (exit 2, never 1) ---------
with tempfile.TemporaryDirectory() as td:
    shutil.copy(GATE, os.path.join(td, "outgoing-copy-gate.py"))
    payload = json.dumps({"tool_name": "mcp__x__send_email",
                          "tool_input": {"to": ["a@b.hu"], "subject": "t", "body": "b"}})
    proc = subprocess.run([sys.executable, os.path.join(td, "outgoing-copy-gate.py")],
                          input=payload.encode(), capture_output=True)
    check("missing email_extract.py: send BLOCKED with exit 2 (1 would run the send unchecked)",
          proc.returncode == 2, f"exit={proc.returncode} stderr={proc.stderr[:200]!r}")
    payload = json.dumps({"tool_name": "Bash",
                          "tool_input": {"command": 'sendmail a@b.hu --body "x"'}})
    proc = subprocess.run([sys.executable, os.path.join(td, "outgoing-copy-gate.py")],
                          input=payload.encode(), capture_output=True)
    check("missing email_extract.py: Bash send BLOCKED with exit 2",
          proc.returncode == 2, f"exit={proc.returncode}")

# --- 4. recipient extraction (new surface; deterministic-or-deny) ------------
to, cc, bcc, reason = mod.collect_bash_recipients(
    'send.py --to a@b.hu --cc "c@d.hu" --to=\'e@f.hu\' --subject x')
check("bash recipients: quoted/unquoted/= forms, order kept",
      (to, cc, bcc, reason) == (["a@b.hu", "e@f.hu"], ["c@d.hu"], [], None),
      f"got {(to, cc, bcc, reason)!r}")

# EMAILBCCHORGONY903: --bcc is a recipient field like any other -- without it
# in the envelope, an approved letter re-sent WITH a bcc anchored identically.
to, cc, bcc, reason = mod.collect_bash_recipients(
    'send.py --to a@b.hu --bcc "rejtett@x.hu" --subject x')
check("bash recipients: --bcc collected (EMAILBCCHORGONY903)",
      (to, cc, bcc, reason) == (["a@b.hu"], [], ["rejtett@x.hu"], None),
      f"got {(to, cc, bcc, reason)!r}")

to, cc, bcc, reason = mod.collect_bash_recipients('send.py --bcc "$HIDDEN"')
check("bash recipients: $VAR in --bcc -> unreadable_reason",
      reason is not None and "--bcc" in reason, f"got {reason!r}")

to, cc, bcc, reason = mod.collect_bash_recipients('send.py --to "$DEST" --cc c@d.hu')
check("bash recipients: $VAR in --to -> unreadable_reason (never approximate)",
      reason is not None and "shell-behelyettesites" in reason, f"got {reason!r}")

to, cc, bcc, reason = mod.collect_bash_recipients('send.py --cc "$(get-cc)"')
check("bash recipients: $(cmd) in --cc -> unreadable_reason",
      reason is not None and "--cc" in reason, f"got {reason!r}")

check("mcp recipients: list + string + missing (+bcc)",
      mod.collect_mcp_recipients({"to": ["a@b.hu", "b@c.hu"], "cc": "c@d.hu"})
      == (["a@b.hu", "b@c.hu"], ["c@d.hu"], [], None)
      and mod.collect_mcp_recipients({"to": "a@b.hu", "bcc": ["h@x.hu"]})
      == (["a@b.hu"], [], ["h@x.hu"], None)
      and mod.collect_mcp_recipients({}) == ([], [], [], None))

# --- 5. envelope composition (the PR2 hash input) ----------------------------
env = mod.collect_email_envelope(
    "mcp__server-gmail-autoauth-mcp__send_email",
    {"to": ["a@b.hu"], "cc": ["x@y.hu"], "subject": "MCP tárgy",
     "body": "MCP törzs ékezettel: űrhajó."})
check("envelope/mcp: envelope fields present (bcc included), text == copy-gate text",
      env["to"] == ["a@b.hu"] and env["cc"] == ["x@y.hu"]
      and env["text"] == golden["mcp"]["mcp-body-subject"]["text"]
      and env["bcc"] == [] and env["unreadable_reason"] is None, f"got {env!r}")

env = mod.collect_email_envelope(
    "Bash", {"command": 'send.py --to a@b.hu --subject "Teszt tárgy ékezettel" '
                        '--body "Kedves Ügyfelünk! Ez a törzs."'})
check("envelope/bash: text matches golden inline case, recipients literal",
      env["text"] == golden["bash"]["inline-body-subject"]["text"]
      and env["to"] == ["a@b.hu"] and env["unreadable_reason"] is None, f"got {env!r}")

env = mod.collect_email_envelope("Bash", {"command": 'send.py --to "$DEST" --body "x"'})
check("envelope/bash: unreadable recipient propagates as unreadable_reason",
      env["unreadable_reason"] is not None, f"got {env!r}")

env = mod.collect_email_envelope("Read", {"file_path": "/x"})
check("envelope/non-send tool: unreadable, never silently hashable",
      env["unreadable_reason"] is not None)

print()
if failed:
    print(f"{len(failed)} FAILED: {failed}", file=sys.stderr)
    sys.exit(1)
print("All email-extract parity tests passed.")
